// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZenCodingVS
{
    static class Vsix
    {
        public const string Id = "9514d70e-a7b1-4876-847d-b0d2ad0962bf";
        public const string Name = "ZenCoding";
        public const string Description = @"Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "emmet, zencoding, html";
    }
}
